version: '3.7'

networks:
  webnet:
volumes:
  mongodata:

services:
  app:
    container_name: main
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
    command: npm run start:dev
    env_file:
      - .env
    networks:
      - webnet
    depends_on:
      - redis
      - db

  db:
    container_name: mongodb
    image: mongo
    networks:
      - webnet
    volumes:
      - mongodata:/data/db
    restart: unless-stopped

  redis:
    container_name: redis
    image: redis:5
    networks:
      - webnet
